name: Example Actions
run-name: $Testing out GitHub Actions
on: [push]
jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install black
      - name: Run check
        run: black --check .
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install pytest coverage numpy matplotlib

      - name: Run tests and collect coverage information
        run: |
          coverage run -m pytest
          coverage report

      - name: Upload coverage information as an artifact
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: coverage-data
          path: .coverage
  coverage_report:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install coverage

      - name: Download coverage information artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-data

      - name: Generate coverage report and XML file
        run: |
          coverage report
          coverage xml -o coverage.xml

      - name: Upload coverage XML as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml